macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:
  env:
    GRAALVM_VERSION: "22.1.0"
    GRAALVM_HOME: ${HOME}/graalvm-ce-java11-22.1.0/Contents/Home
    CLOJURE_LSP_PLATFORM: macos # used in release script
    CLOJURE_LSP_ARCH: aarch64
    CLOJURE_LSP_XMX: "-J-Xmx6g"
    GITHUB_TOKEN: ENCRYPTED[d6ff8cdc392157f211c754fa0763875434d1bfde0c00a05e48ba9470003a76c14c9213adb80623f81e13f2f0fa8fbd57]
  script: |
    sudo scripts/install-clojure /usr/local

    pushd ~
    if ! [ -d graalvm-ce-java11-22.1.0 ]; then
      curl -O -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.1.0/graalvm-ce-java11-darwin-aarch64-22.1.0.tar.gz
      tar xzf graalvm-ce-java11-darwin-aarch64-22.1.0.tar.gz
    fi
    popd

    gu install native-image || true

    export PATH=$GRAALVM_HOME/bin:$PATH
    java -version

    make native-cli

    arch=${CLOJURE_LSP_ARCH:-amd64}
    archive="clojure-lsp-native-macos-$arch.zip"
    zip "$archive" clojure-lsp
    bb release-artifact "$archive" || true
  binaries_artifacts:
    path: "babashka-*.tar.gz"
